tunnel: 2fd517aa-2c6b-43d8-a4b8-4ac0167bb09f
credentials-file: C:\Users\duyh1\.cloudflared\2fd517aa-2c6b-43d8-a4b8-4ac0167bb09f.json
protocol: http2

ingress:
  # Frontend: shopdee.io.vn -> Next.js port 3000
  - hostname: shopdee.io.vn
    service: http://localhost:3000

  # Backend: api.shopdee.io.vn -> Laravel port 8000
  - hostname: api.shopdee.io.vn
    service: http://localhost:8000

  # Catch-all (bắt buộc phải có)
  - service: http_status:404
